### ISSUE TITLE
Stories not loading

### ISSUE THREAD

**Issue by giohb777** [eni9889/IG-PP-Issues#104]
All stories show like that, sometimes they work but 90% they do not show, tried uninstalling the tweak But the problem is still there, i think it messed up with the Instagram system folder
Screenshot: https://imgur.com/a/FJBAr

**Comment by eni9889** [comment]
Try deleting and installing the Instagram app again. The tweak does not touch the Instagram system folder

**Comment by giohb777** [comment]
Did that several times, tried downgrading the app aswell, did not help.
That started happening as i remember, when I updated instagram++ like few weeks ago.
Till now i cannot see stories
