### ISSUE TITLE
[REQUEST] Confirm before liking a comment

### ISSUE THREAD

**Issue by sickshi** [eni9889/IG-PP-Issues#110]
Just for suggestion of improvement. Can we hv a function of "confirm before liking comments" as well? (Similar to "confirm before liking photos") It prevents us from accidentally clicked on the "like" button in comments. Thanks a lot and looking forward to see this new fantastic function!

**Comment by asimcard** [comment]
I would like this too because for some reason I cannot like comments unless the like photo confirmation is off
