### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by afonso177** [eni9889/IG-PP-Issues#111]
When I try to login using the latest version of IG ++ it’ll tell me I’m not running the latest version of Instagram and that I need to update before logging in.

**Comment by eni9889** [comment]
Is this on JB or sideloaded?

**Comment by afonso177** [comment]
Sideloaded

**Comment by eni9889** [comment]
What version of Instagram are you using?

**Comment by afonso177** [comment]
v10.33_1.8r-63 Duplicate with suffix

**Comment by eni9889** [comment]
Can you show me a screenshot?

**Comment by afonso177** [comment]
When logging in through facebook nothing really hapeens, it simply doesn't login but through the normal login this can be seen:
![screen shot 2017-08-13 at 09 11 28](https://user-images.githubusercontent.com/9403210/29251332-e61999a8-804a-11e7-9a86-bcc125bd6156.png)

**Comment by eni9889** [comment]
Can you login through the official app on the app store?

**Comment by afonso177** [comment]
Yes and can also do so through other IG++'s from like AppValley

**Comment by eni9889** [comment]
Where did you get the IPA you are using?

**Comment by afonso177** [comment]
Here: https://github.com/JMccormick264/InstagramPP/releases

**Comment by JMccormick264** [comment]
Can you try the "No Duplicate" IPA?

**Comment by afonso177** [comment]
Just did to no avail, however I just got it to work, when using iOS App signer, the App short version and App version must be left blank

**Comment by JMccormick264** [comment]
You are on iOS 11?

**Comment by afonso177** [comment]
Yes, iOS11 beta 5 and all of your apps I've installed so far now work perfectlly
