### ISSUE TITLE
[BUG] Instagram Version 

### ISSUE THREAD

**Issue by vivaxviv** [eni9889/IG-PP-Issues#112]
I have two accounts on Instagram and every time I restart the app, it logs me out of one of the accounts. Please fix asap, it's making the app very inconvenient to use and I bought the ad-free subscription.

**Comment by eni9889** [comment]
What IG version and tweak version and jailbreak or sideloaded?

**Comment by vivaxviv** [comment]
IG version 10.30.0 and tweak version 1.8r-66 via jailbreak.

Kind regards,
Vivian Gao

**Comment by eni9889** [comment]
Try to delete the Instagram app and install again
