### ISSUE TITLE
[Bug] Reply Bar covering download button in DM stories

### ISSUE THREAD

**Issue by bangbaew** [eni9889/IG-PP-Issues#122]
Latest version on today. when someone sends me a direct message story, I want to download that story but when I press the download button, the reply window will appear instead of download.

**Comment by eni9889** [comment]
Can you post a screenshot?

**Comment by bangbaew** [comment]
@eni9889 Here it is.
https://s26.postimg.org/uhhjh47k9/IMG_7001.jpg

**Comment by JossMarnez** [comment]
Any update here?
The reply bar still covering the download button, not letting download any DM pic/video.
