### ISSUE TITLE
IG++ version 14.0 got some errors!

### ISSUE THREAD

**Issue by imianthony** [eni9889/IG-PP-Issues#124]
iOS: 11
Non-jailbreak
App: 14.0

The new updated version of IG++ (version 14.0) got some bugs. The “Unfollow without confirm” feature does not work. Please fix this issue!

**Comment by JMccormick264** [comment]
Please add the following to your report:

Jailbreak or non
Tweak version

**Comment by lebaronlouis** [comment]
Hello,
Where to find Instagram++ 14.0 in non jailbreak version?
Thanks.

**Comment by imianthony** [comment]
You need to register to HappyChick. Check out https://builds.io

________________________________

**Comment by lebaronlouis** [comment]
Thanks
