### ISSUE TITLE
[Bug] Mark as Read and Download in DM Stories does not work

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#133]
iOS: 11.1
Non Jail broken
Device: iPod 6th Gen
Tweak: 1.8r-79
App Version: 16.0

When receiving a DM story on some devices, the "Mark As Seen" and "Download" buttons are in the reply box, so every time you go to press on them it presses on the text box and the keyboard comes up making you not able to Mark it as read or download it.

**Comment by rikianastasoski** [comment]
and mine dont even show up, i6 sideloaded 10.3,1
