### ISSUE TITLE
[Bug] Issue opening saved instagram images

### ISSUE THREAD

**Issue by emperortetra** [eni9889/IG-PP-Issues#146]
When ever I saved an instagram image, move it to my computer and try to open it there I get an error message saying "Could not complete your request because of a problem parsing JPEG Data." This is a new error that has recently come up within the last few months for me. (below is a screen shot of the error message when attempting to open an image with photoshop CC 2017.) Windows 10 OS, saving from an iphone 6 plus, ios 10.2 jailbroken, instagram version 18.0, instagram ++ version 1.8r-78. This started happening with previous versions of instagram as far back as 10.30

![capture](https://user-images.githubusercontent.com/32778332/31560626-05ac5398-b023-11e7-8d5d-257fd6311f52.JPG)

**Comment by eni9889** [comment]
Try to rename to PNG
