### ISSUE TITLE
[FEATURE] Dark Mode Enhancement Option

### ISSUE THREAD

**Issue by guy4jesuschrist** [eni9889/IG-PP-Issues#15]
Please add an option to change the interface from the bright white, to a dark grey with altered light text colors to complement the dark interface change. I'm currently using Eclipse to do this, but a native option that is more customizable specific to the app would be much better. Perhaps even allow the user to choose the color that replaces the main white interface, as well as the complementary text color they would like. I've attached a screenshot of what it looks like using Eclipse.
![img_7221](https://cloud.githubusercontent.com/assets/111176/23987862/0be3dbe0-0a02-11e7-982d-8598c8bdef24.PNG)

**Comment by D3m3rion** [comment]
Cool idea, I'd love a blackmode, and I can agree that Eclipse doesn't do it very good

**Comment by JMccormick264** [comment]
I think it would be cool too. Eclipse isn't working well for me either.
