### ISSUE TITLE
[Request] change insights 

### ISSUE THREAD

**Issue by soh20i** [eni9889/IG-PP-Issues#16]
Would be awesome to change insights numbers Information.

**Comment by JMccormick264** [comment]
what do you mean by "insights"?

**Comment by soh20i** [comment]
When you change your account to Business you can look into your "insights" which gives you information about your account (followers region/posts/etc)

Have a look here: https://cdn.fstoppers.com/styles/full/s3/media/2016/07/05/instagram-insights-walkthrough-followers.jpg

**Comment by soh20i** [comment]
hi any news regarding this feature?
i'm willing to pay for it

**Comment by eni9889** [comment]
This will take alot of work so for the time being I will shelf this

**Comment by soh20** [comment]
Hey eni9889 any news for this feature? its been a while lol.

really appreciate if we can have this feature
