### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by BoostFX** [eni9889/IG-PP-Issues#168]
IOS 11.2
about v22-v24
side load 

for like 2,3 weeks I got the issue that profiles don't load when I don't select them directly from the search.  Like opening a profile which is linked unter a pic. Results in endless loading.
Besides that it runs perfectly. Thanks Mates

**Comment by eni9889** [comment]
Can you record a video of this happening?

**Comment by BoostFX** [comment]
Here you go. Thanks for the reply. 

https://streamable.com/vosxq

**Comment by eni9889** [comment]
This will be fixed with an update soon
