### ISSUE TITLE
Crashes on opening

### ISSUE THREAD

**Issue by Zashyy** [eni9889/IG-PP-Issues#171]
iOS: 10.2
IG version: 23.0
Tweak: 1.8r-92

Randomly crashes my app out of nowhere. I opened the app again and it popped up saying the tweak is not supported and I should downgrade it. After attempts at downgrading the tweak AND the IG app it still opens and has that pop up. One option is to "re-launch with tweak" but that crashes the app again. Now I can only use the app if I press "launch without tweak". This never ever happened until now randomly.

**Comment by eni9889** [comment]
Can you send me  the crash report? http://tweakcrashed.com/

**Comment by Zashyy** [comment]
Says I can't send it from my device. But the issue can now be fixed by pressing re-launch with tweak but still crashes and doesn't work sometimes if that helps.

**Comment by eni9889** [comment]
Is this on a jailbroken device?

**Comment by Zashyy** [comment]
Yes it is
