### ISSUE TITLE
Follow Status Does Not Work

### ISSUE THREAD

**Issue by becazieg** [eni9889/IG-PP-Issues#172]
I have the "Show Follow Status" turned on in my settings, but when I go to any profile, it doesn't tell me whether they follow me or not anymore. It used to do that on the previous version, but ever since the new update was released it is no longer working. Please put it back
I am on the latest version of Instagram++ on side loaded.

**Comment by eni9889** [comment]
Latest IG is not compatible with the tweak on  sideloaded
