### ISSUE TITLE
[Bug] crash when regram 1st carousel picture 

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#19]
When trying to regram the first picture in a carousel post, the app crashes. 

Crash log here https://ghostbin.com/paste/qhuyh

Syslog https://ghostbin.com/paste/6ck9u

**Comment by eni9889** [comment]
Hmm interesting will have to look at this. This is on latest IG++ and IG?

**Comment by JMccormick264** [comment]
I just downloaded the newest, r-174, will go check

**Comment by JMccormick264** [comment]
Been fixed. Thank you!
