### ISSUE TITLE
[Bug] Download arrow on Stories has disappeared. IG 28.0

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#201]
iOS: 10.1.1
Jailbreak
App: 28.0
Tweak: 1.8r-105

When viewing stories on the latest instagram update the download arrow to download do not seem to appear. In some cases the "Share" button does not appear as well.  Shown [here](https://puu.sh/z31AF/3bd80641ee.jpg)

**Comment by eni9889** [comment]
Fixed in 1.8r-108
