### ISSUE TITLE
[BUG] So many bugs on latest version 

### ISSUE THREAD

**Issue by siddharthsure** [eni9889/IG-PP-Issues#202]
Nothing works on latest IG. Videos auto play and clicking on auto play crashes. Please fix

**Comment by siddharthsure** [comment]
iOS 10.2 JB. iPhone 6. All latest version

**Comment by eni9889** [comment]
What  else  besides videos?

**Comment by siddharthsure** [comment]
Old carousel issue still not fixed. Carousel posts start with 2nd photo most of the times. And while going through stories one by one, suddenly recommended story of ad appears.
