### ISSUE TITLE
[Feature] Most recent feed

### ISSUE THREAD

**Issue by D3m3rion** [eni9889/IG-PP-Issues#21]
I don't know if it is possible on Instagram, but it would be cool to get the most recent feed back :)

**Comment by JMccormick264** [comment]
What do you mean by "most recent"? Doesn't the app already do that?

**Comment by D3m3rion** [comment]
No, unfortunately not. The feed is based on what your friends like, and Instagram decides, what you see first. Like Facebook, but Facebook ++ adds a most recent feed, so I hoped, it could be implemented in Instagram ++ aswell

**Comment by JMccormick264** [comment]
I like this idea

**Comment by eni9889** [comment]
This is server side and is not possible sadly.

**Comment by D3m3rion** [comment]
I understand, thank you.
