### ISSUE TITLE
IG ++ Crash

### ISSUE THREAD

**Issue by mahmood55745** [eni9889/IG-PP-Issues#212]
Hello

When update your tweaks for latest version to :

SnapPlusSL.zip: 1.7r-6 uatools: 2.2r-20
fbppsl.zip: 1.6r-37 uatools: 2.2r-20
igppsl.zip: 1.8r-117 uatools: 2.2r-20
twppsl.zip: 1.2r-72 uatools: 2.2r-20
wappsl.zip: 1.6r-88 uatools: 2.2r-20

Please update it today, and try to update fast like cydia.

**Comment by eni9889** [comment]
Coming soon. Sideloaded has more issues than Cydia
