### ISSUE TITLE
Issue with Peek-a-book on Instagram++

### ISSUE THREAD

**Issue by jehanmodi9** [eni9889/IG-PP-Issues#214]
I have been facing issues with Hold to Zoom when Peek-a-boo is installed. When you try to invoke the 3D touch to enlarge the photo in the feed, it also invoked the hold to zoom window and then creates a mess. I tried toggling Hold to Zoom off and trying but it dint work. Please help with the issue ! 

Regards,
Jehan ! 

App Version: 30.0

Tweak Version: 1.8r-120

iOS Version: 10.2

Tools Version: 2.2r-20

Config Version: 2.1.8.45

**Comment by charlierip** [comment]
I have the same issue, did you fixed it?
