### ISSUE TITLE
iOS 9.3.3 regram problem

### ISSUE THREAD

**Issue by simonlkch** [eni9889/IG-PP-Issues#216]
I use the newest version of the IG++, I go to IG++ of misc setting and click the 'save caption when regram', the photo can regram, but the caption don't exist in the post, just photo not text.

IOS 9.3.3 JB IPhone 6 plus

**Comment by simonlkch** [comment]
IG++ 1.8r 121
IG 31.0

**Comment by TheNightRider12** [comment]
I am having the same.

**Comment by simonlkch** [comment]
I saw the change log, maybe author will find the other way to solve this issue.
