### ISSUE TITLE
Disable Read Receipts not working in Instagram v34.0

### ISSUE THREAD

**Issue by ciubaca666** [eni9889/IG-PP-Issues#232]
Disable Read Receipts not working in Instagram v34.0 
i have: instagram++ 1.8-121
           uasharedtools 2.2r-24
           ios10.2

downgrading to instagram 33.0 i can confirm that the feature works as intended

**Comment by GrexVibra** [comment]
is everything working? can I update to IG v34?

**Comment by yantoyuwantuno** [comment]
Everything is working on V34.0
