### ISSUE TITLE
[BUG] NYTPhotoViewer clips titles at the bottom on iPhone X

### ISSUE THREAD

**Issue by NSExceptional** [eni9889/IG-PP-Issues#239]
Apparently [2.0.0 supports iPhone X](https://github.com/NYTimes/NYTPhotoViewer/issues/257), are you using the latest version? If so, I might send them a PR to fix this. Basically the title label is below the "safe area" so the left and right edges of the label get clipped by the rounded screen.

**Comment by eni9889** [comment]
can u post a  screenshot?

**Comment by NSExceptional** [comment]
https://imgur.com/a/xUIS4jF

Read image descriptions

**Comment by NSExceptional** [comment]
Excuse me? Why did you close the issue?
