### ISSUE TITLE
[Bug] Pressing on the Download story button crashes the app. App Ver: 43.0

### ISSUE THREAD

**Issue by TheNightRider12** [eni9889/IG-PP-Issues#262]
Jailbreak
IOS: 10.1.1
Instagram Version: 43.0
Instagram Tweak: 1.8r-126
uasharedtools: 2.2r-31

When viewing a story and going to download it, as soon as I press the download button the app crashes.
Crash log here: https://hastebin.com/aciresosov.go

**Comment by 6n6aal** [comment]
IG++ After updating we can not send videos to other applications

**Comment by murizz** [comment]
Can you update this for Electra version? @eni9889

**Comment by 6n6aal** [comment]
Do not let the update stay on .. 9.1 good ios 😉
