### ISSUE TITLE
You can’t see a DM photos whitout doesent’t mark it as seen 

### ISSUE THREAD

**Issue by Lorenzogallone** [eni9889/IG-PP-Issues#263]
When someone send a photo and you see it, whitout press on the double tick, the photo is marked as seen and of course  you can see just one more time (Instagram feature)   Version of ig++ 1.8r 126
Ig (just update) 43.0

**Comment by eni9889** [comment]
Can you try 1.8r-127

**Comment by keung227** [comment]
@eni9889 Can you update the Electra version?

**Comment by Lorenzogallone** [comment]
I need the electra version to try, can you please upgrade also that?
