### ISSUE TITLE
Manually mark stories as seen not working in the latest instagram update 43.0

### ISSUE THREAD

**Issue by ciubaca666** [eni9889/IG-PP-Issues#264]
Jailbreak
iOS: 10.2
Instagram version : v43.0
Instagram Tweak: 1.8r-126
uasharedtools: 2.2r-31

Even though i have the manually mark as seen feature ticket to on, when viewing a story, the story is marked as seen automatically without manually pressing the seen button. 

downgrading the app to 41.0 seem to fix the issue

**Comment by al11588** [comment]
I was going to post this as well. I am on 9.3.3 and it has the same issue.

**Comment by manoelfd** [comment]
Same issue here. iOS 10.2, IG v43.0, IG Tweak v1.8r-127.
