### ISSUE TITLE
Getting constant update message

### ISSUE THREAD

**Issue by Pyragon** [eni9889/IG-PP-Issues#270]
Please use the issues portion of this repo to report any issues you find or for feature requests.

Bugs/Crashes should Include the following and be titled as so and also labled as a bug:

[BUG] Constantly getting an update message

Hello, currently everytime I open the instagram app, I get a notification to update to 1.8r-128 but when I click update and it loads cydia, the version on cydia is 1.8r-126 (after refreshing cydia) and I already have that version.
Apologies if this is maybe a cydia issue.

 iOS Version - 10.3.3
 Instagram Version - 44.0
 IG ++ Tweak Version - 1.8r-126

**Comment by ciubaca666** [comment]
the developer says it's on vacation until may 16 , so no fixes until then https://twitter.com/unlimapps/status/988586828847448064
