### ISSUE TITLE
NYTPhotoViewer clips titles at the bottom of the iPhone X.

### ISSUE THREAD

**Issue by NSExceptional** [eni9889/IG-PP-Issues#278]
Apparently [2.0.0 supports iPhone X](https://github.com/NYTimes/NYTPhotoViewer/issues/257), are you using the latest version? If so, I might send them a PR to fix this. Basically the title label is below the "safe area" so the left and right edges of the label get clipped by the rounded screen.

Dunno why you closed this issue before. It has not been fixed.

**Comment by eni9889** [comment]
This should be fixed on JB version and will be pushed to SL soon
