### ISSUE TITLE
Not working on iPhone X with ++ Tweak Sideloader

### ISSUE THREAD

**Issue by keung227** [eni9889/IG-PP-Issues#283]
I can't use IG++ with ++ Tweak Sideloader.
Can you please update it?
Thank you.

**Comment by eni9889** [comment]
What's not working?

**Comment by keung227** [comment]
All functions are not working as well with latest version of Instagram.
There are no any download button on posts and stories.
Also when I setting up the IG++ settings, the app will crash.
iPhone X, iOS 11.3.1 Thank you.

**Comment by keung227** [comment]
Why still not working? @eni9889
