### ISSUE TITLE
Share sheet via++ does not pop-up when triggered in the latest intagram v46.0

### ISSUE THREAD

**Issue by ciubaca666** [eni9889/IG-PP-Issues#288]
Jailbreak
iOS: 10.2
Instagram version : v46.0
Instagram Tweak: 1.8r-138
uasharedtools: 2.2r-31

When you try to share a post via the share++ arrow the share sheet does not pop=up though you can't share a photo or video using other apps.

**Comment by crackout666** [comment]
I have the same issue. The share++ button only opens the defailtn Instagrsm share options. 

The bug is present for quite some time now.
