### ISSUE TITLE
[BUG] jailbroken ig++

### ISSUE THREAD

**Issue by karaigumon** [eni9889/IG-PP-Issues#29]
Ios 10.2
Ig 10.13
Ig++ 1.7r-177

It won't let me view my friends' stories.  Also whenever I do Touch ID and then cancel, it lets me enter my passcode but the buttons don't appear.  They are pushable if you know where they are though.

**Comment by eni9889** [comment]
Can you please provide some more details about the stories issue?

**Comment by karaigumon** [comment]
Honestly there's not much to say other than whenever I try to open one of my friends' stories, it only plays for a split second and then the app crashes.  Here's a recording if this helps

https://youtu.be/TlxI-ebOuuo

**Comment by JMccormick264** [comment]
Are you jailbroken? If so please send Unlim the crash log you get using the app from www.tweakcrashed.com

**Comment by karaigumon** [comment]
I did
