### ISSUE TITLE
Camera takes picture when adjusting volume even when it's not in camera mode

### ISSUE THREAD

**Issue by Unkn0wnM4n** [eni9889/IG-PP-Issues#298]
Whenever I open Instagram after opening a push notification, when I press the volume buttons to higher or lower the audio, it would take a picture and open the camera side within Instagram. I would have to constantly exit the picture mode and swipe in and back out of it again to make it stop. but still whenever I open a push notification, it will proceed to take pictures without being in camera mode within Instagram and slide it over to it after adjusting volume with side buttons... Any suggestions on why this is happening? or is this something wrong with the tweak itself?

**Comment by eni9889** [comment]
Does this happen when the tweak is uninstalled?

**Comment by Unkn0wnM4n** [comment]
The problem stopped after an update so it works fine now but I never used Instagram without the tweak so I didn't know if it would do it while not modified @eni988
