### ISSUE TITLE
[Bug] Can't save photos on sideloaded (images below)

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#30]
iOS version: (me) 10.1.1

Type: sideload

Tweak: 1.7r-172

Instagram Version: 10.13

Phone: iPhone 6S

A couple of people commented on my repo post on ipahub saying they can't download photos on sideload. It asks to give permission to access the camera library but the option to do that in Settings -> Instagram on sideload is not there. 

Images for sideload [Sideload](https://imgur.com/a/monFc)

What I see on JB [JB](https://imgur.com/a/8ZKDe)

**Comment by hbrogden** [comment]
I'm having this issue iPhone 7 plus

**Comment by bootsM** [comment]
Having same issue here as well on iPH 7+ ios10.2.1 sideload
