### ISSUE TITLE
Instagram++ Ad Removal Issue

### ISSUE THREAD

**Issue by iMalikJ** [eni9889/IG-PP-Issues#301]
I'm no longer able to successfully tweet and remove the ads from Instagram++ for 5 days. When I attempt to use the feature of tweeting a tweet and receiving 5 days of no ads, I am transferred to the Twitter profile of @UnlimApps. However, I already follow the account and I now get the "Failed to tweet and remove ads!" notice.. Before, it would open my twitter with a tweet already made and I just had to post it. I've tried unfollowing @UnlimApps and re-clicking the "tweeting" feature only to follow the account again and receive the same notice. Is this feature no longer available? Can't seem to get rid of the ads and I'm no longer prompted with the tweet as I was given before. 

I mentioned this issue in an email (didn't receive a response) and multiple people have as well on Twitter.
Thanks in advance.

**Comment by SimoneFranceschini** [comment]
I have the same problem with the sideloaded app

iPhone SE
Instagram_v40
