### ISSUE TITLE
Crash Issue while adding picture to story

### ISSUE THREAD

**Issue by tokayto** [eni9889/IG-PP-Issues#302]
I use IG 49.0 and IG++ 1.8r-145 on iOS 9. It crashes every time when i try to add a picture to my story from my gallery.

It only happens with the latest IG update.

**Comment by tokayto** [comment]
IG version: 50.0
IG++ version: 49.0

Taking a picture for story and choose a picture for story from gallery still crashes app.

**Comment by Aakash99rocks** [comment]
I second this , I'm also facing this issue, when I chose to add a story and swipe through the other options such as boomerang, Focus by swiping left the app crashes immediately, please fix this issue soon

**Comment by TheNightRider12** [comment]
@tokayto For your issue, can you update to the latest Instagram++ update and see if you are still able to reproduce this?

**Comment by tokayto** [comment]
@JMccormick264 Unfortunately, it still crashes.

**Comment by TheNightRider12** [comment]
@tokayto And you are trying to upload a photo from your camera roll?

**Comment by TheNightRider12** [comment]
Crash report for @Aakash99rocks "Focus" Story page crash
https://pastebin.com/ppJjaUQs

**Comment by tokayto** [comment]
@JMccormick264 Yes. It crashes even i take a picture for the story through Instagram.

**Comment by tokayto** [comment]
@JMccormick264 Just installed IG++156 now and tested different versions of IG.

With IG version 46 no crashes, works perfectly.
Version 49 and 50 it still crashes.

**Comment by TheNightRider12** [comment]
@tokayto Try updating to the latest uasharedtools tweak and trying it again

**Comment by tokayto** [comment]
@JMccormick264 Problem is solved. It works perfectly. Thank you! 😊
