### ISSUE TITLE
Instagram++ not working

### ISSUE THREAD

**Issue by iSanchez10** [eni9889/IG-PP-Issues#304]
I had Instagram version 50 (I’m now on 51) and currently have the latest Instagram++ and the latest uasharedtools but Instagram++ isn’t working. Changelog says it should’ve been working on 50 so I’m kinda confused. Any help??

**Comment by eni9889** [comment]
jailbreak or sideloaded?

**Comment by iSanchez10** [comment]
Jailbreak
