### ISSUE TITLE
[BUG] Pinch to zoom bug - not centered

### ISSUE THREAD

**Issue by Superkloton** [eni9889/IG-PP-Issues#32]
This is **NOT** a feature by Instagram itself! When IG++ is NOT installed, what you can see on this image is impossible to accomplish:

![img_0024](https://cloud.githubusercontent.com/assets/22617697/24222900/137150de-0f54-11e7-87e2-643043beca85.PNG)

The zoom behaviour is WAY off when IG++ is installed. Please fix this, it's very annoying!

**Comment by eni9889** [comment]
@Superkloton can you show me what it looks like without IG++ installed? Also, can you provide information about your iOS device, firmware version etc.

**Comment by Superkloton** [comment]
Yes absolutely.

With the exact same movement with two fingers (one finger in there lower right corner of the picture, the other directly left of the first finger, moving away slightly upwards) I get it max. to here without IG++ installed:

![img_0026](https://cloud.githubusercontent.com/assets/22617697/24286753/e04e5da4-1076-11e7-8fdd-7e52ca32f3ed.PNG)

With IG++ installed, I can easily make the picture disappear completely upwards so that it is not on the display at all anymore which is definitely not possible without IG++ installed. I can show you a screenshot with an Instagram picture completely pushed out of the display if you want.

I tested this on my **iPhone 6 Plus** on **9.3.3** and later on **10.2** as well and on the **iPhone 6** with **9.3.3**. The screenshot is with 10.2 on my iPhone 6 Plus.
The behaviour is everywhere the same: The up-move is much stronger/faster when IG++ is installed.
