### ISSUE TITLE
Instagram++ Ad Bug

### ISSUE THREAD

**Issue by iMalikJ** [eni9889/IG-PP-Issues#329]
Upon opening Instagram++, I keep getting black-screen advertisements that can’t be closed. I have to close and reopen instagram++ several times before finally getting a working Ad that takes 5 seconds to close out of. Many people are also experiencing this issue.

**Comment by iMalikJ** [comment]
This has gotten so bad that I have to close and re-open instagram++ for almost a full minute to get a working ad. Not very convenient.

**Comment by asimcard** [comment]
I thought it was a glitch not ads. O get black screens too but i have the premium ++ apps. No ads
