### ISSUE TITLE
[Bug] 3D pressing on a notification doesn't give a preview of the image

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#33]
iOS: 10.1.1
Type: Jailbreak
Phone: iPhone 6S
Instagram App: 10.13
Tweak: 1.7r-178

Issue: I used to be able to 3D Touch/view a notification on the lockscreen and have a preview of the post come up. Now what I see is [this image](https://imgur.com/a/vvrq5) when 3D touching a notification. Disregard the banner color. 

Could we be able to preview the image again after 3D touching it along with the normal options that go along with 3D Touch?

**Comment by eni9889** [comment]
@JMccormick264  Does this work if you don't have IG++ installed?

**Comment by JMccormick264** [comment]
Actually it does :( I even tried on my non JB phone, and swiping left and pressing "view" on a notification doesn't preview the post. Maybe it's a Instagram thing?
