### ISSUE TITLE
[FEATURE] Option to deactivate download and regram buttons

### ISSUE THREAD

**Issue by SebastianRasch** [eni9889/IG-PP-Issues#343]
For me, these buttons beneath every image are just superfluous and add unnecessary clutter to the design. Please make them optional so we can hide them. The functionality is in the ++ share button anyway so the separate icons don't even add functionality.

**Comment by scoutds** [comment]
Please make this a reality. The save and regram icons are helpful but do not fit with my Instagram as they are a little less bold then the like comment and flag icons.
