### ISSUE TITLE
Repost and Regram crash. IG 10.14

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#35]
iOS: 10.1.1

Type: IPhone 6S

Status: Jailbreak

Tweak: 1.7r-182

Instagram Version: 10.14

Using the regram and repost option crashes the app. Crash log here [link](https://ghostbin.com/paste/rdedt)

**Comment by dimoca** [comment]
Hello, is possible download pictures dm temporaly (View and delete)?

**Comment by JMccormick264** [comment]
You can download them yes. I don't know about temporarily.
