### ISSUE TITLE
[Enhancement] Disabled DM Read Receipts turned off will not show  red "1"after I read a DM

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#39]
iOS: 10.1.1
Type: Jailbreak
Tweak: 1.7r-187
Instagram Version: 10.16

When I have Disable DM Read Receipts enabled, after I read a DM (but it doesn't show it) when I back out of it the app still shows a red "1" in the top right corner. Could that "1" go away even though the read receipts are turned off?

**Comment by kojuice182** [comment]
This also occurs on iOS 9.3.3

**Comment by asimcard** [comment]
Same happens on my 6S on 10.2
