### ISSUE TITLE
[Request] Manually mark dm messages as read

### ISSUE THREAD

**Issue by WizardMascot** [eni9889/IG-PP-Issues#393]
Allow us to manually mark Instagram messages (DM) as read without having to send a message to do so.

**Comment by eni9889** [comment]
Where would you put the button @WizardMascot

**Comment by WizardMascot** [comment]
I'm not too creative, however next to the image of the person on top of the screen? On the left side so we don't accidentally videochat them..

Thank you very much for answering btw, I genuinely didn't think this thread would be watched lol

**Comment by WizardMascot** [comment]
Any idea if you'll release this any time soon? would be so cool, I'm willing to donate even more (I already bought the tweak obviously)

**Comment by WizardMascot** [comment]
SIR YOU ARE A LEGEND AND I LOVE YOU!!!!!!! THANK YOU SO MUCH
