### ISSUE TITLE
[BUG] Profile pic zooming not working

### ISSUE THREAD

**Issue by siddharthsure** [eni9889/IG-PP-Issues#4]
- [ ]  iOS Version - 8.4

- [ ] Instagram Version - 10.12.0

- [ ] IG ++ Verision - 1.7r-157

Profile picture zooming not working anywhere, even jnside the profile. Nothing happens when i touch and hold the profile picture. Was working before this update. Can't figure out which update broke. Updated Instagram and IG++ at the same time. Thanks

**Comment by JMccormick264** [comment]
what iPhone are you on?

**Comment by siddharthsure** [comment]
Iphone 6

**Comment by JMccormick264** [comment]
It should have 3D touch capabilities. Hmm..I am not sure if that is a OS issue or not.
