### ISSUE TITLE
[Bug] Instagram Crashes When Viewing Stories. Latest Instagram Update

### ISSUE THREAD

**Issue by TheNightRider12** [eni9889/IG-PP-Issues#403]
Jailbroken
App Version: v74.0
Tweak Version: 1.8r-234

Description
Instagram++ crashes when viewing a story a few seconds after opening the Story.

Crash Log from Crash Reporter:
https://hastebin.com/ikayuqosur.js

**Comment by eni9889** [comment]
This should be fixed now please let me know if it isnt @JMccormick264
