### ISSUE TITLE
(Bug) Ig++ flips pictures taken 90* clockwise when sending DM images

### ISSUE THREAD

**Issue by Unkn0wnM4n** [eni9889/IG-PP-Issues#404]
iOS 10.3.2
Instagram version: 73.0
Instagram++ version: 1.8-r238 (Tweak installed from jailbroken device)
Problem:  Whenever I take a picture from within DMs and send them whether it's one time view or kept in chat, the image will be taken 90 degrees clockwise of the current position of the phone. If I'm holding it portrait it will take the image as if I was holding it sideways and take a horizontal picture. It won't crop the image, it just acts as if the camera was rotated that way even though the phone is portrait.

**Comment by eni9889** [comment]
Can you post some videos or screenshots of this @Unkn0wnM4n
