### ISSUE TITLE
unlimited accounts function isn’t working anymore on IG++

### ISSUE THREAD

**Issue by blessrle** [eni9889/IG-PP-Issues#406]
You can only sign in to 5 accounts

**Comment by dequinha** [comment]
its no true
i have 8

**Comment by dequinha** [comment]
> You can only sign in to 5 accounts

its no true
i have 8

**Comment by realguyclarke** [comment]
This sucks 😮😢 The main reason why I used it. I really hope they bring it back!!

**Comment by realguyclarke** [comment]
> > You can only sign in to 5 accounts
> 
> its no true
> i have 8

You must have some sort a special app then because I have downloaded and re-downloaded this a crossed five different phones and none of them allow more than five accounts

**Comment by dequinha** [comment]
> > > You can only sign in to 5 accounts
> > 
> > 
> > its no true
> > i have 8
> 
> You must have some sort a special app then because I have downloaded and re-downloaded this a crossed five different phones and none of them allow more than five accounts

[https://www.dropbox.com/s/wzpbp094alahqnz/Foto%2024-12-18%2020%2024%2011.jpg?dl=0](url)

**Comment by dequinha** [comment]
> > > You can only sign in to 5 accounts
> > 
> > 
> > its no true
> > i have 8
> 
> You must have some sort a special app then because I have downloaded and re-downloaded this a crossed five different phones and none of them allow more than five accounts

hahahah nothing special
i have right a 8 accounts with ig++

https://www.dropbox.com/s/wzpbp094alahqnz/Foto%2024-12-18%2020%2024%2011.jpg?dl=0
