### ISSUE TITLE
IG++ Doesn't Send Notifications

### ISSUE THREAD

**Issue by becazieg** [eni9889/IG-PP-Issues#41]
I turned all notifications on in settings and within the app, but the tweak does not send notifications once i have a new dm or comment, etc... The real Instagram app usually does but when I have the tweak I don't receive any to my phone.
I am on iPhone 6s and the version of my tweak is the recent for the ig app version 10.18.
Even a few older versions of IG++ did not have notifications.

**Comment by JMccormick264** [comment]
Are you on JB or sideload? I am receiving notifications fine on JB

**Comment by becazieg** [comment]
Sideload, I'm not jailbroken

**Comment by eni9889** [comment]
No notifications on sideloaded
