### ISSUE TITLE
[Bug] Downloading Photos - Sideloaded

### ISSUE THREAD

**Issue by masdajwdfe** [eni9889/IG-PP-Issues#42]
![img_3905](https://cloud.githubusercontent.com/assets/28237500/25568783/f9a9e3de-2dd8-11e7-84d0-a49634170743.PNG)
![img_3907](https://cloud.githubusercontent.com/assets/28237500/25568784/fe044be0-2dd8-11e7-9c01-bb66372dadd0.PNG)

Downloading photos does not work. When I have the "Auto Select Highest Quality" setting on then  I get the error message "unsupported URL" when I try to download a picture. When the quality setting is off, then the only option it gives me for image size is "0 x 0". This is the thumbnail quality. This is IOS 10.3.1. The Instagram version is 10.18. The tweak version is 1.7r-118 Duplicate. It is sideloaded.

**Comment by JMccormick264** [comment]
Can you try the newest version on my repo? r-190. See if that fixes your issue. If not let me know.
