### ISSUE TITLE
[BUG] I can’t download photos/videos

### ISSUE THREAD

**Issue by Santigf12** [eni9889/IG-PP-Issues#444]
iOS Version : 12.2
Instagram Version : 90.0
IG ++ Tweak Version : 1.8r-244
Tools Version : 2.2r-76
Crash Report : No
Sideloaded : Yes

Each time I try to download a picture or video it’s says it failed...and it doesn’t seem work every time...
![F94B0045-B7A1-4410-AE47-A938E3BA6389](https://user-images.githubusercontent.com/50410927/57378835-e199b400-71a5-11e9-88f5-dbca01d56544.jpeg)

**Comment by ycarogabriel** [comment]
Same here
