### ISSUE TITLE
[BUG] IG ++ asks for a confirmation when i double tap a photo, but not when i click the heart button on the bottom left of the picture.

### ISSUE THREAD

**Issue by karaigumon** [eni9889/IG-PP-Issues#45]
iOS Version: 10.2
Instagram Version: 10.21IG ++ Tweak Version: 1.7r-190
Crash Report: No crashes occur
This issue is on my jailbroken phone.

video (just in case): https://youtu.be/8yBTh4_X9t0

**Comment by JMccormick264** [comment]
do you have the setting "Confirm double tap to like" enabled under IG++ Settings > Feed Settings?

**Comment by JMccormick264** [comment]
Ah. I see. So it is not asking you to double tap to like when you press the heart. But it does when you double tap the image?

**Comment by karaigumon** [comment]
when i double tap the image to like it gives me a confirmation like it should.  But when i click the heart (which only requires one click as it shuold) it doesnt give me a confirmation.  So when people click the heart (once) it should ask for a confirmation

& the confirmation option should be named "confirm to like" since you dont have to double tap the heart to like.

**Comment by JMccormick264** [comment]
Thank you. Will label this now as a bug

**Comment by karaigumon** [comment]
alright thanks!  Think this will be fixed soon?

also i know I said jailbreak, but this MIGHT also be a problem for Sideloaded (im not sure) so check there too just in case
