### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by tylercain** [eni9889/IG-PP-Issues#47]
I bought the thing that allows me to not have ads but every time the app closes it logs me out and I have to log in every time and fix the settings.

**Comment by JMccormick264** [comment]
How did you install the app? Via impactor?

**Comment by JMccormick264** [comment]
This has been happening to others as well. Unlim is aware. He will be looking into it.

**Comment by JMccormick264** [comment]
Pleas Try the latest one on my repo. It has been fixed.
