### ISSUE TITLE
[BUG] INSTAGRAM CRASHES WHEN OPEN STORY in 1.8r-305

### ISSUE THREAD

**Issue by raporcu** [eni9889/IG-PP-Issues#492]
Hi,
instagram crashes when click it by pressing the small profile picture to view story while on the main feed screen. Also, it crashes when enter profile and open story. But no problem if i view the story from the top of the main screen(story feed big circles). I tried 136.0/135.1/135.0 same but 134.0 works perfectly. There is no other tweak I use on Instagram.

iOS 13.3
7 Plus+

**Comment by sivrish** [comment]
I'm also facing the same issue

iOS 13.2.3
iPhone X

**Comment by NunoMF** [comment]
I have the same problem and i have the last version of instagram++ 

IOS 13.3 
iPhone XR

**Comment by kingyyy** [comment]
same even when downgrade IG to 135

IOS 12.4
Iphone XS MAX

**Comment by jjv** [comment]
Same issue, tried versions 135.0, 135.1 and 136.0 w/ latest IG++.

The bug manifests itself also via Own profile > Archive stories.

iOS 13.3
iPhone XS

**Comment by kingyyy** [comment]
fixed when downgrade IG to 134.0.

IOS 12.4
Iphone XS MAX

**Comment by NunoMF** [comment]
Last update fix the issue on latest version of instagram 136
