### ISSUE TITLE
[Bug] Pressing on a user's profile does not enlarge the picture 

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#50]
iOS 10.1.1
Jailbreak
Tweak: 1.7r-191
Instagram Version: 10.22

When pressing or long pressing on a user's profile, their picture does not get bigger. It just stays the same. I think I remember before that if you long press or press on a user's profile picture that the picture will become larger so you can view it better.

**Comment by eni9889** [comment]
Which view is this on?

**Comment by JMccormick264** [comment]
Issue has been fixed.
