### ISSUE TITLE
[BUG] Video Controls on latest version of ++ and Instagram 

### ISSUE THREAD

**Issue by uussaammaahh** [eni9889/IG-PP-Issues#51]
Jailbroken
Instagram: 10.22
Tweak. 1.7r-192

When there are 2 or more videos in 1 post. The videos don't play when the "do not play videos automatically" is on and also the video controls do not show up if "show video controls" is on.

**Comment by JMccormick264** [comment]
Sideload or JB? And what Instagram and tweak version are you on?

**Comment by uussaammaahh** [comment]
@JMccormick264 Using JailBroken and I am on 10.22 of Instagram and 1.7r-192 of Instagram ++

**Comment by JMccormick264** [comment]
Thank you. I went ahead and added that into the report.

**Comment by wildbirds** [comment]
#58 same as my bug...
My solution is downgrade ig version to 10.19

**Comment by eni9889** [comment]
@wildbirds can you send me a link to a post that has multiple videos on a carousel?

**Comment by wildbirds** [comment]
@eni9889 please check these:
https://instagram.com/p/BRW-j_dBI6F/
https://instagram.com/p/BRy5-PLjS6v/
https://instagram.com/p/BRy7IggD-8Z/

**Comment by eni9889** [comment]
@wildbirds is this still an issue? The controls show for me on latest version on beta.unlimapps.com

**Comment by uussaammaahh** [comment]
@eni9899 yes it's still an issue I'm on the latest of everything right now. 4th July 2017 11:46 am
