### ISSUE TITLE
[Bug] Cannot open photos in grid view

### ISSUE THREAD

**Issue by adreano17** [eni9889/IG-PP-Issues#511]
iOS 13.3 AND 13.5.1
IG Version 147.0.0.30.121
IG ++ 1.8r.328 (current)
Crash Report: N/A - not crashing. Just not functioning as intended. 
Jailbreak

Can long-press media to view photo, but cannot single press to bring up page, comments, etc. 

This has been going for about a month and a half now. Tried to work on downgrading IG. Isolated last version working is 144.0. Tweak breaks starting at 145.0. I have been diligently refreshing for an update, but nothing yet. Long time supporter - please look into this.

**Comment by eni9889** [comment]
@adreano17 this should be fixed now

**Comment by adreano17** [comment]
Works great now. Thanks for looking into.
