### ISSUE TITLE
Ad Removal - Logs Out When Closed

### ISSUE THREAD

**Issue by Manchesterr** [eni9889/IG-PP-Issues#55]
There appears to be an issue, which has been present in the last few versions. 

I log in, to remove the ads. When the app is closed, it logs you out, so ads are then shown.  You're still signed into Instagram, just the ads. 

Current version:-
uasharedtools: 2.1r-67
Tweak: 1.7r-192
App: 10.22.0
iOS: 10.3.1

**Comment by eni9889** [comment]
Where did you install the app from?
