### ISSUE TITLE
Downloading photos does not work

### ISSUE THREAD

**Issue by Burnwood1911** [eni9889/IG-PP-Issues#56]
is everyone facing problem of downloading photos instagram ++ in quality selection i get 0x0 and when i click it it downloads low quality blurry photos.

plus i am using the latest version

**Comment by Burnwood1911** [comment]
why wont you answer regading this problem

**Comment by JMccormick264** [comment]
Reopened this issue. I am getting this error "Select Image Size 0x0" on my iPad. It could be a iPad issue @eni9889 on my iPhone JB it's fine. my iPad is non JB.

**Comment by JMccormick264** [comment]
The fix as of now is to turn on "Auto Select Highest Quality Under IG++ --> Media Saving --> "Auto Select  Highest Quality".

**Comment by marcusw89** [comment]
Also having this issue on my non jailbroken iPhone. If I use the fix above I get unsupported URL.

**Comment by eni9889** [comment]
@marcusw89 can you post the details of your IG++ install from IG++ settings -> Contact/More

**Comment by eni9889** [comment]
Should be fixed in latest version let me know if it isnt
