### ISSUE TITLE
[BUG] Pinch to zoom not centered

### ISSUE THREAD

**Issue by Superkloton** [eni9889/IG-PP-Issues#6]
When having IG++ installed, the default pinch to zoom behaviour of Instagram changes. Pictures tend to disappear upwards instead of staying entered.

![img_3700](https://cloud.githubusercontent.com/assets/22617697/23945235/13a0c802-0976-11e7-98d5-befda55798e3.PNG)

**Comment by eni9889** [comment]
This is a feature of Instagram itself

**Comment by Superkloton** [comment]
No it works fine without IG++ installed! See att. screenshot, this never happens when IG++ is NOT installed!
This is a bug report, not a feature request.
