### ISSUE TITLE
[BUG] Following status is no longer displayed

### ISSUE THREAD

**Issue by siddharthsure** [eni9889/IG-PP-Issues#63]
Following status is not displaying in user profile. 
IOS: 8.4 Jailbroken. 
IG++: 1.7r.195
IG version: latest.

**Comment by JMccormick264** [comment]
Happening to me as well on version 10.25

**Comment by uussaammaahh** [comment]
Same here

**Comment by kojuice182** [comment]
Also occur on iOS 9.3.3 jailbroken
