### ISSUE TITLE
[Bug] Save Caption on ReGram does not save the caption 

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#71]
iOS: 10.1.1
Type: Jailbroken
Instagram: 10.25
Tweak: 1.8r-1

I have "Save caption on ReGram" turned on, but when I ReGram a post, the caption/text, that they put into the text box for a post does not copy over when I use that option. The caption of the post I ReGramed does not show up.

**Comment by kojuice182** [comment]
This also occurs on iOS 9.3.3
