### ISSUE TITLE
[BUG] Even with "Follow Status" in the ++ settings enabled, it still doesn't show me whether people followed me or not

### ISSUE THREAD

**Issue by karaigumon** [eni9889/IG-PP-Issues#74]
[ ] iOS Version 10.2 
[ ] Instagram Version 10.25
[ ] IG ++ Tweak Version 1.8r-8
[ ] Crash Report: none
[ ] Jailbreak 

Happens whenever I visit any profile.  There is no green or red text that shows the follow status like it should

**Comment by JMccormick264** [comment]
can you try uninstalling the tweak, running iCleaner and reinstalling it?

**Comment by karaigumon** [comment]
Just tried.  Still doesn't work

**Comment by eni9889** [comment]
@karaigumon which iphone are you using?

**Comment by eni9889** [comment]
also if you downgrade the tweak does it work?

**Comment by karaigumon** [comment]
I am using an iPhone 6s.  I downgraded as far as 1.7r-162 and it still does not show.

**Comment by firascriss7** [comment]
Me too! I have the same issue!
Tried every single ++ version and downgraded the Instagram app multiple time… still no luck 😕

**Comment by firascriss7** [comment]
iPhone 6s also on 9.2 if that matters

**Comment by D3m3rion** [comment]
I'm on iPhone 6s with iOS 10.2 and have the same problem.
It only shows the following status for some profiles.
Might be those who have it set to public, and it's not working on private profiles.
Just a theory though

**Comment by firascriss7** [comment]
I agree! The new privet profiles UI is different that's why is not working but it does work with public profiles which i see that it doesn't have that new UI design

**Comment by firascriss7** [comment]
I think you should do it like Rocket for Instagram does it! In the top of the profile by the username… just saying 😄

**Comment by eni9889** [comment]
@firascriss7 I'll take a look
