### ISSUE TITLE
[Bug] Disable video auto play on videos that are saved not working 

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#84]
iOS: 10.1.1
Jailbreak
Instagram: 10.26
Tweak: 1.8r-20

Video posts that are saved still auto play even though "Disable video auto play" is enabled. It works for feed videos though. Just not for saved posts that are videos.

**Comment by eni9889** [comment]
This should be fixed now please confirm @JMccormick264
