### ISSUE TITLE
[Request] Story viewing share options

### ISSUE THREAD

**Issue by Aransh** [eni9889/IG-PP-Issues#86]
I hate having to save a story item (photo/video) sending it (usually via whatsapp) and then having to delete the item from my camera roll... It would be nice if you could add a share button, maybe add that as an optiob when tapping the 3 dots on the bottom right of a story.

**Comment by eni9889** [comment]
Will do :)

**Comment by eni9889** [comment]
So I just realized you can already do this by clicking share when the options come up

**Comment by Aransh** [comment]
@Eni9889 what? How? What options? All I'm getting is a save button... tapping it just brings up a loading animation and saves the item

**Comment by Aransh** [comment]
LOVING the new update, thanks a bunch 👌🏽
