### ISSUE TITLE
[FEATURE] Hide follow suggestions and -badge

### ISSUE THREAD

**Issue by Superkloton** [eni9889/IG-PP-Issues#9]
An option to hide follow suggestions in the feed and the badge in the profile (shows how many suggestions are "waiting" for you) would be great!
Most important would be to hide the intrusive follow suggestions in the feed. The badge is certainly just a minor addition to that but still nice to have!

![img_0020](https://cloud.githubusercontent.com/assets/22617697/23946407/9361f5d0-097a-11e7-9c6b-e46e32b966d5.PNG)

**Comment by drunk0ffhate** [comment]
Would love to see the suggestions hidden as well, especially in the feed.
