### ISSUE TITLE
[Bug] Notification for Default media destination alert not showing up

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/IG-PP-Issues#93]
Jailbreak
Instagram: 10.29
Tweak: 1.8r-34

When having default media saving location enabled, I do not get the alert when saving photos from my feed (not story). in 1.8r-30 [Image Here](https://puu.sh/wGi99/30c79ca966.png)
On IG 10.29 I do not get the alert when having the default save location enabled. All I see is "Success" and not the alert like it should have according to the release notes for 1.8r-30

**Comment by eni9889** [comment]
Ahh this is not for photos. For photos you can share using the share button
