### ISSUE TITLE
[BUG] Quick Media Download Controls Missing

### ISSUE THREAD

**Issue by darrickteng** [eni9889/IG-PP-Issues#97]
iOS Version: 9.33
Instagram Version: 10.28.0
IG ++ Tweak Version: 1.8r44

Upon install, the quick media download will be available. But after a while (1-3 days), the 2 quick media download buttons on the bottom right of the picture (next to the bookmark button) will disappear

I think this issue is related to the tweak, because it occurs with other Instagram versions too
![img_5548](https://user-images.githubusercontent.com/16842318/28250080-4cd3a508-6a16-11e7-9c23-b9c438bfecaa.JPG)

**Comment by darrickteng** [comment]
It might be related to the Instagram version too. I downgraded to Instagram v10.19.0, and the quick media download buttons returned

I upgraded to Instagram v10.29.0 (the latest), and they are still there. But they will probably disappear after 1-2 days again

**Comment by eni9889** [comment]
Should be fixed on latest version on beta.unlimapps.com
