### ISSUE TITLE
[ISSUE]Save fail

### ISSUE THREAD

**Issue by TylerDurdenLOL** [eni9889/IG-PP-Issues#98]
Every time I attempt to download a video or picture it says it has failed. I just upgraded to 45 hoping it would fix it but it still does not work.

**Comment by TylerDurdenLOL** [comment]
Update: instagram++ 47 came out and still does not fix the problem. Still getting a failed message anytime I click to download

**Comment by eni9889** [comment]
Which version of the Instagram app do you have installed and which iOS version are you on?

**Comment by TylerDurdenLOL** [comment]
Instagram version 10.30 and iOS 9.3.3

**Comment by eni9889** [comment]
@TylerDurdenLOL  can you post a screenshot of what your feed looks like?

**Comment by eni9889** [comment]
@TylerDurdenLOL also are you trying to save to media fault or photos?

**Comment by TylerDurdenLOL** [comment]
Photos, however meadivault doesn't work as well. Im upgrading to 1.8r-48 then i will post screenshot if still having issue

**Comment by TylerDurdenLOL** [comment]
![image](https://user-images.githubusercontent.com/30246744/28327680-00d80502-6b99-11e7-89da-37c3a2e7eede.jpg)

![image1](https://user-images.githubusercontent.com/30246744/28327686-09914258-6b99-11e7-82eb-a7fd8b4ee2f9.jpg)

**Comment by eni9889** [comment]
@TylerDurdenLOL what kind of iPhone is this on?

**Comment by TylerDurdenLOL** [comment]
iPhone 6S

**Comment by eni9889** [comment]
@TylerDurdenLOL can you imessage me at support@unlimapps.com and we can try and dive deeper into this?
